__author__ = 'Andrew'
ESXI_BASE_URL="http://127.0.0.1:8080"
ESXI_CLONE_URL=ESXI_BASE_URL+"/clone/"
ESXI_UPLOAD_VM_URL=ESXI_BASE_URL+"/receive_vm_file/"
<<<<<<< HEAD
ESXI_CHECKALIVE_URL=ESXI_BASE_URL+"/is_alive/"
VIRTUAL_MACHINE_REPO='VirtualMachines/'
=======
ESXI_CREATE_VM_RECORD=ESXI_BASE_URL+"/new/"
VIRTUAL_MACHINE_REPO='VirtualMachineRepo/'
>>>>>>> 7253068a82811fc7731eedfb2257923dc2f70264
